### PR TITLE
Fix return type for generated client methods

### LINKED ISSUE #121: Generated Client method return types
Here's the relevant bit of the WSDL:

```xml
<s:element name="GetReleaseNotes">
    <s:complexType>
        <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="x" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="y" type="s:string" />
        </s:sequence>
    </s:complexType>
</s:element>
<s:element name="GetReleaseNotesResponse">
    <s:complexType>
        <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetReleaseNotesResult" type="tns:GetReleaseNotesResult" />
        </s:sequence>
    </s:complexType>
</s:element>
<s:complexType name="GetReleaseNotesResult">
    <s:complexContent mixed="false">
        <s:extension base="tns:CorpWebResult">
            <s:sequence>
                <s:element minOccurs="0" maxOccurs="1" name="MajorVersions" type="tns:ArrayOfReleaseMajorVersion" />
            </s:sequence>
        </s:extension>
    </s:complexContent>
</s:complexType>
```

My understanding is, `GetReleaseNotesResponse` is a ResultProvider, and as such, I have the following Rule:

```php
->addRule(new TypenameMatchesRule(
    new AssembleRule(new ResultProviderAssembler()),
        '/Response$/'
))
```

This gives me a `GetReleaseNotesResponse` of:

```php
namespace GAA\CorpManagerApi\SoapTypes;

use Phpro\SoapClient\Type\ResultProviderInterface;
use Phpro\SoapClient\Type\ResultInterface;

class GetReleaseNotesResponse implements ResultProviderInterface
{

    /**
     * @var GetReleaseNotesResult
     */
    private $GetReleaseNotesResult = null;

    /**
     * @return GetReleaseNotesResult|ResultInterface
     */
    public function getResult() : \Phpro\SoapClient\Type\ResultInterface
    {
        return $this->GetReleaseNotesResult;
    }
}
```

Now, in the `\Phpro\SoapClient\Client::call()` method, there is [code](https://github.com/phpro/soap-client/blob/5e0f5dd74a0a261db8c73cb669bdc376ad258d50/src/Phpro/SoapClient/Client.php#L97-L99) to skip straight to the `getResult()` value:

```php
if ($result instanceof ResultProviderInterface) {
    $result = $result->getResult();
}
```

When I use `generate:client` command, I get (as one example) a default client method assembler giving me:

```php
public function getReleaseNotes(\GAA\CorpManagerApi\SoapTypes\GetReleaseNotes $GetReleaseNotes) : \GAA\CorpManagerApi\SoapTypes\GetReleaseNotesResponse
{
    return $this->call('GetReleaseNotes', $GetReleaseNotes);
}
```
screenshot 2017-12-30 14 03 34

Note that it's giving a return type of `GetReleaseNotesResponse`, yet the `@return` from `call()` is `ResultInterface`.

My manually created Client that has been working was return type declared as `ResultInterface`.

So my question:

Am I doing something wrong in my setup that is making the generated return type be incorrect, or is the [`returntype` value](https://github.com/phpro/soap-client/blob/5e0f5dd74a0a261db8c73cb669bdc376ad258d50/src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php#L54) in the ClientMethodAssembler incorrect?

Here would be the proposed change if its a bug:

```diff
- 'returntype' => '\\'.$method->getParameterNamespace().'\\'.$method->getReturnType(),
+ 'returntype' => ResultInterface::class,
```

### PR DESCRIPTION
**Pull request by GaryJones**
Fixes #121

### CODE REVIEW

**Comment by veewee** [comment]
Hi @GaryJones,

I prefer not to use the interface as a return type. We'll have to investigate how we can fix this in a better way.

**Comment by GaryJones** [comment]
> I prefer not to use the interface as a return type.

Understood, but in this case, it's the only agreed (contracted) certainty (without any other changes).

**Comment by veewee** [comment]
About the result provider issue. might something as this work?

- Add ClientMethodOptions as constructor argument to the ClientMethodAssembler class in which you can specify which class to return.
- When a class has been registered in the options : use that class - otherwise use the automatically generated one.

This way you can customize the way it works by using the ClientMethodMatchesRule and possibly by adding a `ClientMethodMapRule` that works like the `TypeMapRule`.

Then you could do something like this:

```php
return Config::create()
    ->addRule(
        new Rules\ClientMethodMapRule(
            [
                'ClientMethod1' => new Rules\AssembleRule(new Assembler\ClientMethodAssembler(
                        (new ClientMethodAssemblerOptions())->withReturnType(SomeReturnType::class)
                    )
                ),
                'ClientMethod2' => new Rules\AssembleRule(new Assembler\ClientMethodAssembler(
                        (new ClientMethodAssemblerOptions())->withReturnType(ResultInterface::class)
                    )
                )
            ],
            new Rules\AssembleRule(new Assembler\ClientMethodAssembler(new ClientMethodAssemblerOptions()))
        )
    );
```

Or easier to configure:

```php
// This could be in a separate file:
$clientMethodMap = [
    'ClientMethod1' => SomeReturnType::class,
    'ClientMethod2' => ResultInterface::class,
    'ClientMethod3' => ResultInterface::class,
    'ClientMethod4' => ResultInterface::class,
    'ClientMethod5' => ResultInterface::class,
    'ClientMethod6' => ResultInterface::class,
    'ClientMethod7' => ResultInterface::class,
    'ClientMethod8' => ResultInterface::class,
];

return Config::create()
    ->addRule(
        new Rules\ClientMethodMapRule(
            array_map(
                function($methodReturnType) {
                    return new Rules\AssembleRule(new Assembler\ClientMethodAssembler(
                        (new ClientMethodAssemblerOptions())->withReturnType($methodReturnType)
                    );
                },
                $clientMethodMap
            ),
            new Rules\AssembleRule(new Assembler\ClientMethodAssembler(new ClientMethodAssemblerOptions()))
        )
    );

```


What do you think?

**Comment by GaryJones** [comment]
This was never really about having the ability to change what return type was used; it was about the automatic value being incorrect when ResultProviders are present.

Saying that...

I think the `ClientMethodAssemblerOptions` approach can initially be done without the mapping extras.

```php
// Client method created with correct concrete type (which is the bug still to be fixed)
->addRule( new Rules\ClientMethodMatchesRule(
    new Rules\AssembleRule(new Assembler\ClientMethodAssembler(
       (new ClientMethodAssemblerOptions())
    )
    '/^ClientMethod1$/'
) 

// ...or if ClientMethodAssemblerOptions is made optional
->addRule( new Rules\ClientMethodMatchesRule(
    new Rules\AssembleRule(new Assembler\ClientMethodAssembler(),
    '/^ClientMethod1$/'
) 

// ----

->addRule( new Rules\ClientMethodMatchesRule(
    new Rules\AssembleRule(new Assembler\ClientMethodAssembler(
       (new ClientMethodAssemblerOptions())->withReturnType(ResultInterface::class)
    ),
    '/^ClientMethod1$/'
) // Client method returns a different type.
```

In my case, this won't really help, since when I need to return a type that is the interface, it's because I'm also changing the body of the method.

----

We don't need the above to solve #121. My "lazy" solution of defaulting to the interface is perhaps not sufficient here, but the logic should be on getting a better version of `'returntype' => '\\'.$method->getParameterNamespace().'\\'.$method->getReturnType(),` so that it _automatically_ accounts for ResultProviders.

Can we consistently determine what the Result class will be, from a ResultProvider? i.e.:
```
// pseudo-code

$returnType = '\\'.$method->getParameterNamespace().'\\'.$method->getReturnType();
if ( method_exists( `getResult`, $returnType ) {
    $returnType = get_class(new $returnType())->getResult());
}
```

**Comment by janvernieuwe** [comment]
Sounds like a job for https://secure.php.net/manual/en/function.is-subclass-of.php to me ;)

**Comment by janvernieuwe** [comment]
Perhaps something like this might do the trick, as long as you have a return type.
```
<?php

class Bar {}

class Test {
    public function foo(): Bar
    {

    }
}
$function = new ReflectionClass(Test::class);
echo $function->getMethod('foo')->getReturnType();
```

**Comment by veewee** [comment]
Not really, the `ResultProvider` is added by an assembler. We can't assume the types exist yet while creating the client. The only way to determine what the method should return is by explicitly specifying it. The same goes with registering ResultProviders to types, but for types it is easier since it can have the same class for multiple regex matches.

@GaryJones : Agree - the regex can also be used for the same purpose, but is less maintainable. But it is sufficient.

Conclusion: While using ResponseProviders on types and client methods, you always need to explicitly set the return type somehow. Be it by using a regex rule or a map rule.

**Comment by GaryJones** [comment]
Clearly, this needs a bit more thought. Would you be willing to accept this PR, so we at least get a valid return type, even if not quite ideally implemented, and then work on a "better" solution?

> The client generator is mostly used to generate a lot of code which can be customized afterwards. You could add custom assemblers, but I am not sure this has any advantages over generating the client once and adding custom functionallity to it.

There absolutely is value in not having to do manual customisations. The API I happen to be working with has recently pulled a previously public method out of its unversioned API 😱️. Being able to do `composer generate`, and have client, classmap and types be automatically generated correctly, and not then have to customise further, is what I'm after. There are multiple folks working on this package, and to expect them to know how to do any manual customisations after a fresh generation is unreasonable. What I've got working is fantastic (thank you!), so trying to get those fixes upstream to here is the next logical step.

**Pull request closed without merging**
