### PR TITLE
Bump version of laminas to 4.5.0

### PR DESCRIPTION
**Pull request by pottink**
Signed-off-by: Jelle Deneweth <jelle.deneweth@gmail.com>

### CODE REVIEW

**Comment by jdreesen** [comment]
I don't think this is necessary.

**Comment by pottink** [comment]
> I don't think this is necessary.

When using --prefer-lowest with composer it would still install 4.4.0 thus not compatible on PHP8.1.

**Comment by jdreesen** [comment]
Are you sure it'll use `4.4.0` when running `--prefer-lowest` on PHP 8.1? 
I think composer will install the minimal working version for the PHP version you're running.

**Comment by veewee** [comment]
I think @jdreesen has a valid point here ... 
If we bump the dependency, other projects need to upgrade laminas-code as well - which is still quite fresh.

Lets keep the dependency as-is for now. Nevertheless thanks for the PR : it points oit that the new version of laminas-code doesnt introduce any issues inside this repo!

**Pull request closed without merging**
