### PR TITLE
Array type hint v1.7.x

### PR DESCRIPTION
**Pull request by sippsolutions**

### CODE REVIEW

**Comment by sippsolutions** [comment]
@veewee I cherry-picked the commits from #408 into the branch v1.7.x

**Comment by veewee** [comment]
Thanks!

**Comment by sippsolutions** [comment]
@veewee Thanks for merging - do you have an ETA of v1.7.2? :)

**Comment by veewee** [comment]
Released https://github.com/phpro/soap-client/releases/tag/v1.7.2

**Comment by sippsolutions** [comment]
@veewee Cool, thank you! :)

**Pull request merged**
