### PR TITLE
#446: Do not use TypeChecker in FluentSetterAssembler.

### PR DESCRIPTION
**Pull request by yenyasinn**
See https://github.com/phpro/soap-client/issues/446

### CODE REVIEW

**Comment by veewee** [comment]
Thanks for the PR.
It looks like there is still an occurence somewhere?

**Comment by yenyasinn** [comment]
Yes, it is used in ClientMethodAssembler

**Comment by yenyasinn** [comment]
No, please have a look https://github.com/phpro/soap-client/blob/master/src/Phpro/SoapClient/CodeGenerator/Assembler/ClientMethodAssembler.php#L217. 
It some another case.

**Comment by veewee** [comment]
@janvernieuwe Do you remember why that check was added to the `ClientMethodAssembler`?
The linked ticket in #406 doesn't seem related to the fix?

It seems like we can drop the `TypeChecker` if we change the logic inside the `ClientMethodAssembler`.

I was thinking about changing


https://github.com/phpro/soap-client/blob/9c616b677df4c7038a17a5c5390becadf3f7b55e/src/Phpro/SoapClient/CodeGenerator/Model/ClientMethod.php#L88-L91

To make it work more like 

https://github.com/phpro/soap-client/blob/9c616b677df4c7038a17a5c5390becadf3f7b55e/src/Phpro/SoapClient/CodeGenerator/Model/Property.php#L64-L71

That way, we could check for the trailing `\` or if the fqcn contains a `\` to return the skip.
Internally it will behave smarter, since it will use both the list of reserved keywords and Type suffixer.

What do you think?

**Comment by janvernieuwe** [comment]
@veewee It is related to the fix, if i recall correctly it tried to use root (\) for internal types like string.
Your suggested fix looks good to me, a test was also added to check for regression on this so we should be good.

**Pull request closed without merging**
